// ArchetypeNode.cs — generated by Archetype.Build; do not edit
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Godot;
using Archetype.Build;
using Archetype.Core;
using Archetype.Engine;

/// <summary>
/// Generated Godot node that hosts a <c>GameSession</c> and bridges the async
/// action loop to GDScript via signal/method pairs (D33).
/// </summary>
[GlobalClass]
public partial class ArchetypeNode : Node
{
	// --- Engine lifecycle signals ---
	[Signal] public delegate void ActionRequestedEventHandler(string playerName, Godot.Collections.Dictionary availableActions);
	[Signal] public delegate void ActionResolvedEventHandler();
	[Signal] public delegate void PromptRequestedEventHandler(string playerName, string promptType, Godot.Collections.Dictionary context);
	[Signal] public delegate void GameOverEventHandler(string winnerName);
	[Signal] public delegate void GameErrorEventHandler(string message);

	// --- Derived keyword signals ---
	[Signal] public delegate void OnHealEventHandler(long target, double amount);
	[Signal] public delegate void OnStrikeEventHandler(long target, double power);

	// --- Session state ---
	private Task? _runTask;
	private CancellationTokenSource? _cts;
	private GameStateView? _stateView;

	// Per-player suspension: one TCS per outstanding SelectAction / RespondToPrompt call.
	private readonly Dictionary<string, TaskCompletionSource<PlayerAction?>> _pendingActions = new();
	private readonly Dictionary<string, TaskCompletionSource<PromptResponse>> _pendingPrompts = new();

	// --- Session startup ---

	/// <summary>
	/// Loads the game definition and card sets from the generated JSON files,
	/// then starts the game session.
	/// </summary>
	/// <param name="hostManifestData">Session-specific overrides; pass an empty
	/// <c>Dictionary</c> if none are needed.</param>
	/// <param name="definitionPath">Resource path to <c>game_definition.json</c>.</param>
	/// <param name="cardSetPaths">Array of resource paths to card-set JSON files.</param>
	public void StartGame(
		Godot.Collections.Dictionary hostManifestData,
		string definitionPath = "res://archetype/game_definition.json",
		Godot.Collections.Array? cardSetPaths = null)
	{
		var jsonOptions = GameDefinitionJsonOptions.Build();
		var defJson = FileAccess.GetFileAsString(definitionPath);
		var definition = JsonSerializer.Deserialize<GameDefinition>(defJson, jsonOptions)!;

		var cardSets = new List<CardSet>();
		var paths = (cardSetPaths == null || cardSetPaths.Count == 0) ? LoadDefaultCardSetPaths() : cardSetPaths;
		foreach (var path in paths)
		{
			var json = FileAccess.GetFileAsString(path.ToString()!);
			var set = JsonSerializer.Deserialize<CardSet>(json, jsonOptions);
			if (set != null) cardSets.Add(set);
		}
		definition = definition.WithCardSets(cardSets);

		_cts = new CancellationTokenSource();
		var builder = GameSession.Create(definition)
			.WithRandomSource(new Archetype.Engine.SeededRandom(GD.Randi()));

		builder = builder.WithPlayerStrategy("alice", new InnerStrategy("alice", this));
		builder = builder.WithPlayerStrategy("bob", new InnerStrategy("bob", this));

		var session = builder.Build();
		_runTask = RunLoopAsync(session, _cts.Token);
	}

	private static Godot.Collections.Array LoadDefaultCardSetPaths()
	{
		var result = new Godot.Collections.Array();
		var dir = DirAccess.Open("res://archetype/card-sets/");
		if (dir == null) return result;
		foreach (var file in dir.GetFiles())
			if (file.EndsWith(".json"))
				result.Add($"res://archetype/card-sets/{file}");
		return result;
	}

	private async Task RunLoopAsync(GameSession session, CancellationToken ct)
	{
		try
		{
			var result = await session.RunAsync(ct);
			// winnerName is empty string for a draw (D33 spec).
			EmitSignal(SignalName.GameOver, result.Winner ?? string.Empty);
		}
		catch (System.OperationCanceledException)
		{
			// Normal shutdown: node exited tree while game was running.
		}
		catch (System.Exception ex)
		{
			GD.PrintErr("[ArchetypeNode] engine error: ", ex.Message, "\n", ex.StackTrace);
			EmitSignal(SignalName.GameError, ex.Message);
		}
	}

	/// <summary>Cancels the game loop when the node leaves the scene tree.</summary>
	public override void _ExitTree()
	{
		_cts?.Cancel();
		_cts?.Dispose();
		_cts = null;
	}

	// --- GDScript-callable action submission methods ---

	/// <summary>Submits a play-card action for the named player.</summary>
	public void SubmitPlayCard(string playerName, long cardAtomId, Godot.Collections.Dictionary costChoices)
	{
		if (!_pendingActions.TryGetValue(playerName, out var tcs)) return;
		var choices = DictionaryToStringObject(costChoices);
		tcs.TrySetResult(new PlayCard(new AtomId(cardAtomId), choices));
	}

	/// <summary>Submits an activate-ability action for the named player.</summary>
	public void SubmitActivateAbility(string playerName, long sourceAtomId, string effectName, Godot.Collections.Dictionary costChoices)
	{
		if (!_pendingActions.TryGetValue(playerName, out var tcs)) return;
		var choices = DictionaryToStringObject(costChoices);
		tcs.TrySetResult(new ActivateAbility(new AtomId(sourceAtomId), effectName, choices));
	}

	/// <summary>Submits a pass action for the named player.</summary>
	public void SubmitPass(string playerName)
	{
		if (!_pendingActions.TryGetValue(playerName, out var tcs)) return;
		tcs.TrySetResult(new Pass());
	}

	/// <summary>Submits a prompt response for the named player.</summary>
	public void SubmitPromptResponse(string playerName, Godot.Collections.Dictionary response)
	{
		if (!_pendingPrompts.TryGetValue(playerName, out var tcs)) return;
		var chosen = new System.Collections.Generic.List<object>();
		foreach (var key in response.Keys)
			chosen.Add(response[key]);
		tcs.TrySetResult(new ChoiceResponse(chosen));
	}

	// --- Post-action signal emission ---

	/// <summary>
	/// Iterates <paramref name="events"/> (depth-first) and emits a hardcoded
	/// GDScript signal for every event whose keyword name is in the derived set.
	/// </summary>
	private void EmitDerivedSignals(System.Collections.Generic.IReadOnlyList<GameEvent> events)
	{
		foreach (var root in events)
		foreach (var ev in root.SelfAndDescendants())
		{
			switch (ev.KeywordName)
			{
				case "heal":
					EmitSignal(SignalName.OnHeal
						, (long)(AtomId)(ev.BoundArgs["target"])
						, (double)(ev.BoundArgs["amount"])
					);
					break;
				case "strike":
					EmitSignal(SignalName.OnStrike
						, (long)(AtomId)(ev.BoundArgs["target"])
						, (double)(ev.BoundArgs["power"])
					);
					break;
			}
		}
	}

	private static System.Collections.Generic.Dictionary<string, object> DictionaryToStringObject(
		Godot.Collections.Dictionary dict)
	{
		var result = new System.Collections.Generic.Dictionary<string, object>(StringComparer.Ordinal);
		foreach (var key in dict.Keys)
			result[key.ToString()!] = dict[key];
		return result;
	}

	// --- GDScript-callable state query methods (D38) ---

	/// <summary>Returns the named accumulator value for the given atom, or 0.0 if no state is available.</summary>
	public double GetAccumulator(long atomId, string name) => _stateView?.GetAccumulator(new AtomId(atomId), name) ?? 0.0;

	/// <summary>Returns whether the named condition is set on the given atom, or false if no state is available.</summary>
	public bool HasCondition(long atomId, string name) => _stateView?.HasCondition(new AtomId(atomId), name) ?? false;

	/// <summary>Returns the named computed property for the given atom, or 0.0 if no state is available.</summary>
	public double GetComputedProperty(long atomId, string name) => _stateView?.GetComputedProperty(new AtomId(atomId), name) ?? 0.0;

	/// <summary>Returns the zone atom ID for the given card atom, or 0L if no state is available.</summary>
	public long GetZone(long atomId) => _stateView != null ? (long)_stateView.GetZone(new AtomId(atomId)) : 0L;

	/// <summary>Returns the owner atom ID for the given atom, or 0L if no state is available.</summary>
	public long GetAtomOwner(long atomId) => _stateView != null ? (long)_stateView.GetOwner(new AtomId(atomId)) : 0L;

	/// <summary>Returns the AtomKind ordinal for the given atom, or -1 if no state is available.</summary>
	public int GetKind(long atomId) => _stateView != null ? (int)_stateView.GetKind(new AtomId(atomId)) : -1;

	/// <summary>Returns all atom IDs of the given AtomKind as an array of longs.</summary>
	public Godot.Collections.Array GetAtoms(int kind)
	{
		var result = new Godot.Collections.Array();
		if (_stateView == null) return result;
		foreach (var id in _stateView.GetAtoms((AtomKind)kind))
			result.Add((long)id);
		return result;
	}

	// --- InnerStrategy — per-player IPlayerStrategy implementation ---

	private sealed class InnerStrategy : IPlayerStrategy
	{
		private readonly string _playerName;
		private readonly ArchetypeNode _node;

		public InnerStrategy(string playerName, ArchetypeNode node)
		{
			_playerName = playerName;
			_node = node;
		}

		public async Task<PlayerAction?> SelectActionAsync(
			AvailableActions available,
			GameStateView state,
			CancellationToken ct = default)
		{
			// Emit derived signals for the just-completed action before opening
			// the next decision window.  LastActionEvents is populated by the
			// engine after all blocks, SBRs, and triggers resolve (D30).
			_node.EmitDerivedSignals(state.LastActionEvents);
			_node.EmitSignal(SignalName.ActionResolved);

			// Serialise available actions to a plain Dictionary for GDScript.
			var availableDict = SerialiseAvailableActions(available);
			var tcs = new TaskCompletionSource<PlayerAction?>(
				TaskCreationOptions.RunContinuationsAsynchronously);
			_node._pendingActions[_playerName] = tcs;
			_node._stateView = state;
			_node.EmitSignal(SignalName.ActionRequested, _playerName, availableDict);

			using var reg = ct.Register(() => tcs.TrySetCanceled());
			return await tcs.Task;
		}

		public async Task<PromptResponse> RespondToPromptAsync(
			PromptContext context,
			GameStateView state,
			CancellationToken ct = default)
		{
			var promptType = context.GetType().Name;
			var contextDict = new Godot.Collections.Dictionary();
			var tcs = new TaskCompletionSource<PromptResponse>(
				TaskCreationOptions.RunContinuationsAsynchronously);
			_node._pendingPrompts[_playerName] = tcs;
			_node._stateView = state;
			_node.EmitSignal(SignalName.PromptRequested, _playerName, promptType, contextDict);

			using var reg = ct.Register(() => tcs.TrySetCanceled());
			return await tcs.Task;
		}

		private static Godot.Collections.Dictionary SerialiseAvailableActions(AvailableActions available)
		{
			var dict = new Godot.Collections.Dictionary();
			var cards = new Godot.Collections.Array();
			foreach (var opt in available.PlayableCards)
				cards.Add((long)opt.Card);
			dict["playable_cards"] = cards;
			var abilities = new Godot.Collections.Array();
			foreach (var opt in available.ActivatableAbilities)
			{
				var entry = new Godot.Collections.Dictionary();
				entry["source"] = (long)opt.Source;
				entry["effect_name"] = opt.EffectName;
				abilities.Add(entry);
			}
			dict["activatable_abilities"] = abilities;
			dict["can_pass"] = available.CanPass;
			return dict;
		}
	}

}
