# archetype_atom_kinds.gd — generated by Archetype.Build; do not edit
## Integer constants for AtomKind values.
## Use with [method ArchetypeInterop.get_atoms] and [method ArchetypeInterop.get_kind].
class_name ArchetypeAtomKinds

const CARD    = 0
const ZONE    = 1
const PLAYER  = 2
const SESSION = 3
