# archetype_keywords.gd — generated by Archetype.Build; do not edit
## String constants for every registered keyword name.
##
## Use these instead of bare strings to avoid typos when referencing
## keywords in code.
class_name ArchetypeKeywords

## Keyword identifier for [b]add[/b].
const ADD = "add"
## Keyword identifier for [b]and[/b].
const AND = "and"
## Keyword identifier for [b]apply-condition[/b].
const APPLY_CONDITION = "apply-condition"
## Keyword identifier for [b]apply-modifier[/b].
const APPLY_MODIFIER = "apply-modifier"
## Keyword identifier for [b]assert[/b].
const ASSERT = "assert"
## Keyword identifier for [b]at-least[/b].
const AT_LEAST = "at-least"
## Keyword identifier for [b]at-most[/b].
const AT_MOST = "at-most"
## Keyword identifier for [b]copy-card[/b].
const COPY_CARD = "copy-card"
## Keyword identifier for [b]create-card[/b].
const CREATE_CARD = "create-card"
## Keyword identifier for [b]create-zone[/b].
const CREATE_ZONE = "create-zone"
## Keyword identifier for [b]declare-draw[/b].
const DECLARE_DRAW = "declare-draw"
## Keyword identifier for [b]declare-winner[/b].
const DECLARE_WINNER = "declare-winner"
## Keyword identifier for [b]equal-to[/b].
const EQUAL_TO = "equal-to"
## Keyword identifier for [b]event-arg[/b].
const EVENT_ARG = "event-arg"
## Keyword identifier for [b]get-atoms-in-zone[/b].
const GET_ATOMS_IN_ZONE = "get-atoms-in-zone"
## Keyword identifier for [b]get-property[/b].
const GET_PROPERTY = "get-property"
## Keyword identifier for [b]get-state[/b].
const GET_STATE = "get-state"
## Keyword identifier for [b]greater-than[/b].
const GREATER_THAN = "greater-than"
## Keyword identifier for [b]has-condition[/b].
const HAS_CONDITION = "has-condition"
## Keyword identifier for [b]heal[/b].
const HEAL = "heal"
## Keyword identifier for [b]in-zone[/b].
const IN_ZONE = "in-zone"
## Keyword identifier for [b]less-than[/b].
const LESS_THAN = "less-than"
## Keyword identifier for [b]max[/b].
const MAX = "max"
## Keyword identifier for [b]min[/b].
const MIN = "min"
## Keyword identifier for [b]modify-accumulator[/b].
const MODIFY_ACCUMULATOR = "modify-accumulator"
## Keyword identifier for [b]move-card[/b].
const MOVE_CARD = "move-card"
## Keyword identifier for [b]multiply[/b].
const MULTIPLY = "multiply"
## Keyword identifier for [b]not[/b].
const NOT = "not"
## Keyword identifier for [b]or[/b].
const OR = "or"
## Keyword identifier for [b]owner-of[/b].
const OWNER_OF = "owner-of"
## Keyword identifier for [b]player-by-name[/b].
const PLAYER_BY_NAME = "player-by-name"
## Keyword identifier for [b]random-int[/b].
const RANDOM_INT = "random-int"
## Keyword identifier for [b]remove-condition[/b].
const REMOVE_CONDITION = "remove-condition"
## Keyword identifier for [b]remove-modifier[/b].
const REMOVE_MODIFIER = "remove-modifier"
## Keyword identifier for [b]session[/b].
const SESSION = "session"
## Keyword identifier for [b]strike[/b].
const STRIKE = "strike"
## Keyword identifier for [b]subtract[/b].
const SUBTRACT = "subtract"
