# archetype_signals.gd — generated by Archetype.Build; do not edit
## SCREAMING_SNAKE_CASE signal name constants for derived keyword signals.
##
## Use with [method Object.connect] as an alternative to bare strings.
class_name ArchetypeSignals

## Signal name constant for [b]on_heal[/b]. See [GameEvents].
const ON_HEAL = "on_heal"
## Signal name constant for [b]on_strike[/b]. See [GameEvents].
const ON_STRIKE = "on_strike"
