# card_atom.gd — generated by Archetype.Build; do not edit
## Typed view wrapper for Card atoms (D40).
## Use [method ArchetypeInterop.get_card] to obtain instances.
class_name CardAtom
extends RefCounted

var _atom_id: int

## Creates a new [CardAtom] wrapping [param atom_id].
static func _create(atom_id: int) -> CardAtom:
    var obj := CardAtom.new()
    obj._atom_id = atom_id
    return obj

## Returns the raw engine atom ID.
func get_atom_id() -> int:
    return _atom_id

## Returns the zone atom ID this card currently occupies.
func get_zone_id() -> int:
    return ArchetypeInterop.get_zone(_atom_id)

## Returns the owner player atom ID.
func get_owner_id() -> int:
    return ArchetypeInterop.get_atom_owner(_atom_id)

func get_health() -> float:
    return ArchetypeInterop.get_accumulator(_atom_id, "health")

