# card_atom.gd — generated by Archetype.Build; do not edit
## Typed view wrapper for Card atoms (D40).
## Use [method ArchetypeInterop.get_card] to obtain instances.
class_name CardAtom
extends RefCounted

var _atom_id: int

## Creates a new [CardAtom] wrapping [param atom_id].
static func _create(atom_id: int) -> CardAtom:
	var obj := CardAtom.new()
	obj._atom_id = atom_id
	return obj

## Returns the raw engine atom ID.
func get_atom_id() -> int:
	return _atom_id

## Returns the definition name this atom was instantiated from.
func get_definition_name() -> String:
	return ArchetypeInterop.get_definition_name(_atom_id)

## Returns a static property from this atom's definition, or empty string if absent.
func get_static_property(key: String) -> String:
	return ArchetypeInterop.get_static_property(_atom_id, key)

## Returns all static property keys defined on this atom's definition.
func get_static_property_keys() -> Array[String]:
	return Array(ArchetypeInterop.get_static_property_keys(_atom_id), TYPE_STRING, "", null)

## Returns all accumulators currently set on this atom as [String] → [float].
func get_accumulators() -> Dictionary:
	return ArchetypeInterop.get_accumulators(_atom_id)

## Returns the names of all conditions currently active on this atom.
func get_active_conditions() -> Array[String]:
	return Array(ArchetypeInterop.get_active_conditions(_atom_id), TYPE_STRING, "", null)

## Returns the property names that have at least one active modifier on this atom.
func get_modifier_keys() -> Array[String]:
	return Array(ArchetypeInterop.get_modifier_keys(_atom_id), TYPE_STRING, "", null)

## Returns the zone atom ID this card currently occupies.
func get_zone_id() -> int:
	return ArchetypeInterop.get_zone(_atom_id)

## Returns the zone this card currently occupies.
func get_zone() -> ZoneAtom:
	return ZoneAtom._create(ArchetypeInterop.get_zone(_atom_id))

## Returns the owner player atom ID.
func get_owner_id() -> int:
	return ArchetypeInterop.get_atom_owner(_atom_id)

## Returns the owner player.
func get_owner() -> PlayerAtom:
	return PlayerAtom._create(ArchetypeInterop.get_atom_owner(_atom_id))

## Returns the structured render tree for this card's primary effect.
## Node shape: [code]{"type": "text"|"composite"|"sequence"|"ref", …}[/code].
## Use [code]type[/code] to switch on node kind; [code]composite[/code] carries
## [code]summary[/code] (human-readable) and [code]body[/code] (full expansion).
func get_rules_tree() -> Dictionary:
	return ArchetypeInterop.get_rules_tree(_atom_id)

func get_health() -> float:
	return ArchetypeInterop.get_accumulator(_atom_id, "health")
