# game_events.gd — generated by Archetype.Build; do not edit
## Typed signal declarations for every keyword referenced in card definitions.
##
## Connect to these on [ArchetypeNode] to react to specific game events.
class_name GameEvents

## Emitted when the [b]heal[/b] keyword resolves.
## [param target]: atom ID of the target
## [param amount]: numeric value
signal on_heal(target: int, amount: float)
## Emitted when the [b]strike[/b] keyword resolves.
## [param target]: atom ID of the target
## [param power]: numeric value
signal on_strike(target: int, power: float)
