# render_node.gd — generated by Archetype.Build; do not edit
## Typed wrappers for the rules tree returned by [method CardAtom.get_rules_tree].
##
## Use [method RenderNode.parse] to convert a raw [Dictionary] to a typed node:
## [codeblock]
## var tree := RenderNode.parse(card.get_rules_tree())
## if tree is RenderNode.CompositeNode:
##     label.text = (tree as RenderNode.CompositeNode).summary.flat_text()
## [/codeblock]
class_name RenderNode
extends RefCounted

## Node type discriminator. One of [code]"text"[/code], [code]"composite"[/code],
## [code]"sequence"[/code], or [code]"ref"[/code].
var type: String

## Parses a raw [Dictionary] (as returned by [method CardAtom.get_rules_tree])
## into a typed [RenderNode] subtype.
static func parse(dict: Dictionary) -> RenderNode:
	match dict.get("type", ""):
		"text":      return TextSpan._from(dict)
		"composite": return CompositeNode._from(dict)
		"sequence":  return SequenceNode._from(dict)
		"ref":       return RulesRef._from(dict)
		_:           return TextSpan._from({})

## Returns the flat human-readable text for this node, collapsing all structure.
## Override in each subtype; the base returns an empty string.
func flat_text() -> String:
	return ""

# ---------------------------------------------------------------------------
# Subtypes
# ---------------------------------------------------------------------------

## A leaf node containing a literal string fragment.
class TextSpan extends RenderNode:
	## The string content of this leaf.
	var text: String

	static func _from(d: Dictionary) -> TextSpan:
		var n := TextSpan.new()
		n.type = "text"
		n.text = d.get("text", "")
		return n

	func flat_text() -> String:
		return text

## A keyword invocation with a human-readable [member summary] and a full
## recursive [member body] expansion.
## Render [member summary] for minimal display; show [member body] as a tooltip.
class CompositeNode extends RenderNode:
	## Human-readable rendering from the resolved template (locale-aware).
	var summary: RenderNode
	## Full recursive expansion of the keyword composition tree.
	var body: RenderNode

	static func _from(d: Dictionary) -> CompositeNode:
		var n := CompositeNode.new()
		n.type = "composite"
		n.summary = RenderNode.parse(d.get("summary", {}))
		n.body = RenderNode.parse(d.get("body", {}))
		return n

	func flat_text() -> String:
		return summary.flat_text()

## An ordered list of child [RenderNode]s.
## Separator and list formatting are the host's responsibility.
class SequenceNode extends RenderNode:
	## The ordered child nodes. Each element is a [RenderNode] subtype.
	var items: Array

	static func _from(d: Dictionary) -> SequenceNode:
		var n := SequenceNode.new()
		n.type = "sequence"
		n.items = []
		for item in d.get("items", []):
			n.items.append(RenderNode.parse(item))
		return n

	func flat_text() -> String:
		var parts: Array[String] = []
		for item in items:
			parts.append((item as RenderNode).flat_text())
		return " ".join(parts)

## An inline cross-reference to a keyword definition.
## The host renders it as an interactive link; when activated,
## resolve it via [method ArchetypeInterop.resolve_keyword_text].
class RulesRef extends RenderNode:
	## The keyword name to resolve.
	var key: String
	## The text shown to the player for this link.
	var display: String

	static func _from(d: Dictionary) -> RulesRef:
		var n := RulesRef.new()
		n.type = "ref"
		n.key = d.get("key", "")
		n.display = d.get("display", "")
		return n

	func flat_text() -> String:
		return display
