# session_atom.gd — generated by Archetype.Build; do not edit
## Typed view wrapper for Session atoms (D40).
## Use [method ArchetypeInterop.get_session] to obtain instances.
class_name SessionAtom
extends RefCounted

var _atom_id: int

## Creates a new [SessionAtom] wrapping [param atom_id].
static func _create(atom_id: int) -> SessionAtom:
    var obj := SessionAtom.new()
    obj._atom_id = atom_id
    return obj

## Returns the raw engine atom ID.
func get_atom_id() -> int:
    return _atom_id

