# zone_atom.gd — generated by Archetype.Build; do not edit
## Typed view wrapper for Zone atoms (D40).
## Use [method ArchetypeInterop.get_zone_atom] to obtain instances.
class_name ZoneAtom
extends RefCounted

var _atom_id: int

## Creates a new [ZoneAtom] wrapping [param atom_id].
static func _create(atom_id: int) -> ZoneAtom:
    var obj := ZoneAtom.new()
    obj._atom_id = atom_id
    return obj

## Returns the raw engine atom ID.
func get_atom_id() -> int:
    return _atom_id

## Returns the owner player atom ID.
func get_owner_id() -> int:
    return ArchetypeInterop.get_atom_owner(_atom_id)

